name: Tests

on: [ push ]

jobs:
  test:
    runs-on: ubuntu-latest
    services:
      mysql:
        image: mysql:8.0
        env:
          MYSQL_DATABASE: ${{ secrets.DB_NAME }}
          MYSQL_USERNAME: ${{ secrets.DB_USERNAME }}
          MYSQL_PASSWORD: ${{ secrets.DB_PASSWORD }}
          MYSQL_ROOT_PASSWORD: ${{ secrets.DB_PASSWORD }}
        options: --health-cmd="mysqladmin ping" --health-interval=10s --health-timeout=5s --health-retries=3
        ports:
          - 3306:3306
    steps:
      - name: Create mysql user
        run: |
          mysql --host 127.0.0.1 --port 3306 -uroot -p${{ secrets.DB_PASSWORD }} \
            -e "DROP USER IF EXISTS '${{ secrets.DB_USERNAME }}';" \
            -e "CREATE USER '${{ secrets.DB_USERNAME }}'@'%' IDENTIFIED BY '${{ secrets.DB_PASSWORD }}';" \
            -e "GRANT ALL PRIVILEGES ON *.* to '${{ secrets.DB_USERNAME }}'@'%';"
      - uses: actions/checkout@v3
      - name: Setup Java 11
        uses: actions/setup-java@v3
        with:
          java-version: '11'
          distribution: 'adopt'
          architecture: x64
      - name: Setup Gradle
        uses: gradle/gradle-build-action@v2
      - name: Run tests
        run: |
          env
          ./gradlew test
        env:
          SERVER_PORT: 4242
          DB_HOST: 127.0.0.1
          DB_PORT: 3306
          DB_NAME: ${{ secrets.DB_NAME }}
          DB_USERNAME: ${{ secrets.DB_USERNAME }}
          DB_PASSWORD: ${{ secrets.DB_PASSWORD }}
